CREATE TABLE accounts (
  account_id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  account_type VARCHAR(20) DEFAULT 'Client',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
